#pragma once

#include "core/Types.h"

#include <juce_dsp/juce_dsp.h>

#include <memory>
#include <vector>

namespace am
{

//==============================================================================
/**
    Stereo short-time Fourier transform: Hann analysis window, 75 % overlap
    (hop = size / 4), Hann synthesis window, weighted overlap-add.

    The pair of channels shares one frame clock so the two spectra handed to the
    processing callback always belong to the same instant.

    Latency is exactly `size()` samples: a frame is complete once its last input
    sample has arrived, and the first output sample of that frame is emitted on
    the following input sample.

    Everything is preallocated in `prepare()`; `process()` allocates nothing.
*/
class STFT
{
public:
    /** Allocates for the given FFT size (a power of two). Call from prepare(). */
    void prepare (int fftSize);

    /** Clears all history. The next `size()` output samples will be silence. */
    void reset();

    int size() const noexcept    { return fftSizeValue; }
    int hop() const noexcept     { return hopSizeValue; }
    int numBins() const noexcept { return fftSizeValue / 2 + 1; }
    int latency() const noexcept { return fftSizeValue; }

    /**
        Streams `n` samples through the transform and writes the resynthesised
        (wet) result to `outL` / `outR`.

        `fn (float* specL, float* specR, int numBins)` is invoked once per hop.
        The spectra are JUCE real-only FFT buffers: interleaved (re, im) pairs,
        bins 0 … numBins-1 are meaningful (bin 0 = DC, numBins-1 = Nyquist).
        Whatever the callback leaves there is resynthesised.

        When `active` is false no transform runs (the output is silence) but the
        input history keeps filling, so enabling the effect resumes instantly.
    */
    template <typename FrameFn>
    void process (const float* inL, const float* inR, float* outL, float* outR,
                  int n, bool active, FrameFn&& fn)
    {
        const int fifoOffset = fftSizeValue - hopSizeValue;

        for (int i = 0; i < n; ++i)
        {
            inFifo[0][(size_t) rover] = inL[i];
            inFifo[1][(size_t) rover] = inR[i];
            outL[i] = outFifo[0][(size_t) (rover - fifoOffset)];
            outR[i] = outFifo[1][(size_t) (rover - fifoOffset)];

            if (++rover >= fftSizeValue)
            {
                rover = fifoOffset;
                runFrame (active, fn);
            }
        }
    }

private:
    template <typename FrameFn>
    void runFrame (bool active, FrameFn&& fn)
    {
        const int n = fftSizeValue;
        const int h = hopSizeValue;
        const int bins = numBins();

        if (active)
        {
            for (int ch = 0; ch < 2; ++ch)
            {
                auto* fb = fftBuf[ch].data();
                const auto* in = inFifo[ch].data();
                const auto* w = window.data();
                for (int k = 0; k < n; ++k) fb[k] = in[k] * w[k];
                std::fill (fb + n, fb + 2 * n, 0.0f);
                fft->performRealOnlyForwardTransform (fb, true);
            }

            fn (fftBuf[0].data(), fftBuf[1].data(), bins);

            for (int ch = 0; ch < 2; ++ch)
            {
                auto* fb = fftBuf[ch].data();
                // The negative-frequency half is regenerated by the inverse transform;
                // clear it so every FFT backend sees a well-defined buffer.
                std::fill (fb + 2 * bins, fb + 2 * n, 0.0f);
                fft->performRealOnlyInverseTransform (fb);

                auto* acc = outAccum[ch].data();
                const auto* w = window.data();
                for (int k = 0; k < n; ++k) acc[k] += fb[k] * w[k] * synthScale;
            }
        }

        for (int ch = 0; ch < 2; ++ch)
        {
            auto* acc = outAccum[ch].data();
            std::memcpy (outFifo[ch].data(), acc, sizeof (float) * (size_t) h);
            std::memmove (acc, acc + h, sizeof (float) * (size_t) (n - h));
            std::fill (acc + (n - h), acc + n, 0.0f);

            auto* in = inFifo[ch].data();
            std::memmove (in, in + h, sizeof (float) * (size_t) (n - h));
        }
    }

    std::unique_ptr<juce::dsp::FFT> fft;
    std::vector<float> window;
    std::vector<float> inFifo[2], outFifo[2], outAccum[2], fftBuf[2];
    int fftSizeValue = 1024;
    int hopSizeValue = 256;
    int rover = 768;
    float synthScale = 2.0f / 3.0f;  ///< 1 / Σ w² for a periodic Hann at 75 % overlap
};

} // namespace am
